---
- name: gitlab.rb modify ldap server address
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
   - name: replace text file
     replace:
       dest: /tmp/gitlab.rb
       regexp: '100.102.145.80'
       replace: '100.102.145.79'
       backup: yes
        

   # - lineinfile:
   #     path: /tmp/gitab.rb
   #     regexp: '^host: '100.102.145.79''
   #     line: 'host: 'aaa.aaa.aaa.aaa''
