- name: gitlab.rb modify ldap server address
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:  
    - lineinfile:
        path: /tmp/gitab.rb
        regexp: '^host: '100.102.145.79''
        line: 'host: 'aaa.aaa.aaa.aaa''
